### ISSUE TITLE
Connect button

### ISSUE THREAD

**Issue by blkluv** [Zhixuan0318/Emissary#1]
Hi, the connect Subwallet button on the connect your wallet to proceed isn't working. Nothing is clickable.

**Comment by Zhixuan0318** [comment]
Hi @blkluv 👋 Thanks for raising up the issue. Yes, we are currently configuring something at the backend, that's why the button is currently not working. I will update you in this issue and close this as complete once solved 👍

**Comment by Zhixuan0318** [comment]
<img width="950" alt="image" src="https://github.com/Zhixuan0318/Emissary/assets/69501009/0c1faf48-9e6b-456c-b26d-76ea4172251c">

Hi @blkluv, I had checked the issue that you had mentioned. The connect wallet button is working as usual since beginning and not affected by the server configuration we are carrying out. Maybe you can try to check whether you had installed the SubWallet extension. If not, you can simply  [go here](https://www.subwallet.app/) and download it~ 

Since the connect wallet button is working perfectly, I will close this issue.
